### ISSUE TITLE
Set The Date manually after object is created

### ISSUE THREAD

**Issue by bathan** [dmuy/DCalendar#1]
I have a form where I use the plugin for several fields. If I change the textbox value using javascript the plugin shows using "today" as current value and Im not able to find the way to work around this.

Is there any way I can some function so it triggers the "selectedDate" event with a custom value?

**Comment by dmuy** [comment]
Hi bathan,

I've updated the js file to facilitate what you need. After you update the textbox value just call `$('#myinput').dcalendarpicker('setDate');`, where myinput is the id of your textbox.

**Comment by bathan** [comment]
Hey! Thanks a lot for this change! It does work but now I have a different problem. Im using latin american date format `{format: 'dd/mm/yyyy'}` . When I create the dcalendarpicker object I specify that format. 

So the text input has a value of `03/08/2016` for today , and when I run your new function its changed to `8/3/2016` 

Apparently the problem is in `value = new Date(that.calendar.prev().val());` inside `setDate` function . I believe maybe you should check date format before creating the Date object?

Sorry for the annoyance and thanks a lot again for taking time to look at this.

**Comment by dmuy** [comment]
Hi, actually I've tried the format you're using and it's running fine. Can you post the snippet of your code where you set the date and call the function I made?

**Comment by bathan** [comment]
HI! 
The code is built using a blade template in laravel, that is why its mixed with php code.

``````
$('#{{ "st_".strtolower($stage_name)."_starts_at" }}').focus(function(e) {
                    if($(this).val() == '' ) {
                        var previous_stage = $(this).data('previous-stage-name');
                        if (previous_stage) {
                            var prev_finish_date = $('#st_' + previous_stage + '_ends_at').val();
                            if (prev_finish_date) {

                                $(this).val(prev_finish_date);
                                $(this).dcalendarpicker('setDate');
                            }
                        }
                    }
                });```

The fields are date ranges for a process different stages. Each stage has a start and end date, and the idea here is to "suggest" a start date that will be the value of the previos stage end date. So when the user focuses on the field, it checks if it has a `data-previous-step-name` and gets the value from that input box.

Thanks!

``````

**Comment by dmuy** [comment]
Hi,

There shouldn't be any problem with the format as I always call the format function.
If you initially defined the format of your date input like: `$('#{{ "st_".strtolower($stage_name)."_starts_at" }}').dcalendarpicker({format: 'dd/mm/yyyy'})`, there shouldn't be any problem with the formatting.
And I assume your date input is static and not dynamically added.

**Comment by bathan** [comment]
Im initializing the plugin like this :

$('#{{ "st_".strtolower($stage_name)."_starts_at"
}}').dcalendarpicker({format: 'dd/mm/yyyy'});
$('#{{ "st_".strtolower($stage_name)."_ends_at"
}}').dcalendarpicker({format: 'dd/mm/yyyy'});

Ill look into it tomorrow. Thanks!!

**Comment by bathan** [comment]
What I was able to debug is that in the setDate function :

setDate : function() {
   var that = this,
      value = new Date(that.calendar.prev().val());

if the date is for example today : 05/08/2016 , witch according to the
format is August 5 2016, it gets converted to May 8 2016. Attaching some
screenshots of the Chrome Developer Tools

Value of the text input : 05/08/2016

[image: Inline image 1]

Value of the `value` variable witch was converted to May 08 2016 instead.

[image: Inline image 2]

Hope this helps!

**Comment by dmuy** [comment]
Oh, right. That's the problem, initializing new Date object using different format. I'll look into this to find a solution. Thanks :)

**Comment by dmuy** [comment]
Hi @bathan, I've updated the js file. I added a handler for the parsing of date value. Hope this helps. :)

**Comment by bathan** [comment]
Yay! It works like a charm!! Thanks a lot!!!
