### ISSUE TITLE
PAST DATE SHOULD BE ABLE TO DISABLE 

### ISSUE THREAD

**Issue by iamjeerge** [dmuy/DCalendar#2]
Is there any option to Disable previous dates ?

**Comment by dmuy** [comment]
Hi @gururajjeerge, currently there is no option to disable dates, but I've made something like this in my other projects I just didn't reflect the changes in this version. I made it so the user can specify the min and max dates.

How do you want to disable it? Like disable the dates earlier than today?

**Comment by iamjeerge** [comment]
Hi,
Yes your correct.

I want to disable dates past from today.

**Comment by dmuy** [comment]
Hi @gururajjeerge,

I updated the css and js to facilitate the min & max date option.
You just need to specify data-mindate with the value "today" or a specific date using `mm/dd/yyyy` format.

For example:
`<input type="text" id="mydatepicker" data-mindate="today">`
or
`<input type="text" id="mydatepicker" data-mindate="08/10/2016">`
