### ISSUE TITLE
How to set minDate and maxDate

### ISSUE THREAD

**Issue by hithaieshl** [dmuy/DCalendar#3]
Hi dmuy,
I was searching for a jquery date picker with min date and max date setting option and i came across your plugin, can you please explain how to set minDate and maxDate. 
Thank you.

**Comment by dmuy** [comment]
Hi @hithaieshl ,

You just need to specify **data-mindate** or **data-maxdate** with the value "today" or a specific date using `mm/dd/yyyy` format.

For example:
`<input type="text" id="mydatepicker" data-mindate="today">`
or
`<input type="text" id="mydatepicker" data-mindate="08/10/2016">`
