### ISSUE TITLE
Calls this.reformatDate before setting this.options, crashes

### ISSUE THREAD

**Issue by default-kramer** [dmuy/DCalendar#4]
Here on line 29 it can call reformatDate, but it doesn't set this.options until line 34, leading to a "cannot read property of undefined" error.

https://github.com/dmuy/DCalendar/blob/a5226d719f887622a8803993c3cbbf13d0bf57b4/dcalendar.picker.js#L29

I fixed by moving line 34 near the top, seems to work fine.

**Comment by dmuy** [comment]
Hi @default-kramer,

Thanks for reporting this, I also saw this one but didn't have the time to update the code. I've already pushed the updates for this one and other issues I've seen. Thanks again.
