### ISSUE TITLE
Change event not firing

### ISSUE THREAD

**Issue by default-kramer** [dmuy/DCalendar#5]
With &lt;input type="text"&gt; the change event does not fire. It looks like a typo here - "onchange" should be "change"

https://github.com/dmuy/DCalendar/blob/a5226d719f887622a8803993c3cbbf13d0bf57b4/dcalendar.picker.js#L335

**Comment by dmuy** [comment]
Hi @default-kramer,

Actually this is for ASP.Net, because I was working with an ASP.Net application and figured it doesn't call the postback for the ontextchange event. So I added this code. The code just below it is for non-ASP.Net applications.
