### ISSUE TITLE
datechanged event is not fired

### ISSUE THREAD

**Issue by leo-unglaub** [dmuy/DCalendar#6]
Hey,
i wanted to listen to your datechanged event but currently its never triggered. I used the following code:

```js
<script>
  $(document).ready(function(){
    $('#datepicker').dcalendarpicker({format: 'mm-dd-yyy'}).on('datechanged', function(e){
      console.log (e);
    });
  });
</script>
```

The calendar gets attached to the input field but when i select something in it the event is never fired. I would need this so i could update values in my vuejs instance after the user selected a date.

Thanks and greetings
Leo

**Comment by dmuy** [comment]
Hi @LeoUnglaub,

Are you using the material (version 2) date picker or the original (version 1)?

If the snippet you provided doesn't work, I'm assuming you're using the original version. If so, you need to change the event `datechanged` to `dateselected`.

**Comment by leo-unglaub** [comment]
Hey,
you where completely right about this. I just copied the example event name from your docs but of course i was in the wrong version.

Sorry about than and thanks!
Greetings
Leo
