### ISSUE TITLE
Date Format unchangable

### ISSUE THREAD

**Issue by darrelRayen** [dmuy/DCalendar#7]
Hi Is there a way to change the default date format. I tried *format: 'dd/mm/yyyy'*
But still the date is picked as mm/dd/yyyy. Please can you help me on this.

**Comment by dmuy** [comment]
Hi @darrelGapstar,

Can you show me how you initialized the date picker? I tried the latest revision and it's working fine. The `format` configuration works fine.

I initialized the date picker like this: 
`$('#datepicker').dcalendarpicker({ format: 'mmm dd, yyyy'});`

**Comment by darrelRayen** [comment]
Hi @dmuy ,
Thank you for responding.
I'm actually using the  1.1 and DCalendar Picker 1.3 plugin (not the latest).  This is how I implemented it.
 $('#calendar-demo').dcalendar(); 
 $('#calendar-demo').dcalendarpicker({ format: 'dd-mm-yyyy'});

I want the format to be like 31/07/2017

**Comment by dmuy** [comment]
Hi @darrelGapstar,

You initialized the same element twice? 
If `#calendar-demo` is just one element you can just use the 2nd line. And to change the format, write something like this: `{ format: 'dd/mm/yyyy' }`.

`$('#calendar-demo').dcalendarpicker({ format: 'dd/mm/yyyy'});`

If you used the same id on different elements, you should change the id for the first line (which creates a calendar instead of a date picker).

**Comment by darrelRayen** [comment]
Hi @dmuy 
Actually when I remove the $('#calendar-demo').dcalendar(); the calendar is not getting initialized in the front end.

**Comment by dmuy** [comment]
Hi @darrelGapstar,

I've also tried the latest revision of [version 1](https://github.com/dmuy/DCalendar/tree/master) and it's working just fine.

Are you using it on plain html or php or something else?

**Comment by darrelRayen** [comment]
Hi @dmuy ,

yes I/m using it on plain html5 . I'm still having the issue.. I will try using the latest revision.

**Comment by darrelRayen** [comment]
Hi.

is there a way to high light the selected date in this plugin.Please help.

**Comment by dmuy** [comment]
Hi @darrelGapstar,

What do you mean? The selected date already has a highlight (in blue).
![image](https://user-images.githubusercontent.com/8830886/31573123-ab6d35f8-b0e7-11e7-8530-0ebfcf213b69.png)

**Comment by darrelRayen** [comment]
But when I select a date it doesn't get highighted (in blue) like you've mentioned. Sorry Im new to Jquery

**Comment by dmuy** [comment]
Hi @darrelGapstar,

It's not actually on the jQuery part, but on the css. Maybe you have a conflicting style on this class `.calendar .selected`.

You should be able to see the following line in the css file.
![image](https://user-images.githubusercontent.com/8830886/31576768-655ea964-b134-11e7-8056-c94e58c4b0a7.png)

**Comment by darrelRayen** [comment]
Hi,

Thank you for promptly responding for the issues. When I click the date the
color changes as you have mentioned. But it's only on click. for a second .
then it's changed. Still it's an issue with conflicting css ?


*Thanks & Regards*


*Darrel Rayen*
*Jr Software Engineer| **M*: +94 778476428 <+94771304626>| *@*:
darrel@gapstars.net <rumesh@gapstars.net>

*Gapstars*
621, 2nd Floor, Nawala Road, Rajagiriya, Sri Lanka | *T*: +94 11 4502542
<+94114502542> | *W*: https://www.gapstars.net <http://www.gapstars.net/>

**Comment by dmuy** [comment]
Hi @darrelGapstar,

If you are using the latest version (given you have no conflicting css), the highlight on selected date should work properly.
