### ISSUE TITLE
date change event in dcalendar

### ISSUE THREAD

**Issue by memePushpendu** [dmuy/DCalendar#8]
How can get get the date clicked from dcalendar  ???

**Comment by dmuy** [comment]
Hi @memePushpendu,

Are you using the version 1? 
If so, to get the clicked date on the calendar use the `selectdate` event:
`$('#mycalendar').dcalendar().on('selectdate', function (e) { alert(e.date); });`

If you are referring to the date picker, use the `dateselected` event:
`$('#mydatepicker').dcalendarpicker().on('dateselected', function (e) { alert(e.date); });`

If you are using version 2, use the following events for calendar and date picker respectively: `dateselected` and `datechanged`.
