### ISSUE TITLE
a Big Bug!

### ISSUE THREAD

**Issue by 152016726** [dmuy/DCalendar#9]
Hey Sir,look at these,what the hell with you with below?why do you write the ';' after 'var cal = that.calendar'. God Damed!Thanks and Fu,ck,you!!!
LOOK AT THIS :-1: var cal = that.calendar;
				curr = cal.find('.calendar-dates'),
				dayLabel = cal.find('.calendar-labels'),
				currMonth = cal.find('.calendar-curr-month'),
				container = cal.find('.calendar-date-holder'),
				cElem = curr.clone(),
				rows = [], cells = [], count = 0;

**Comment by dmuy** [comment]
@152016726, I'm sorry can you explain to me what bug this is? Because to me this is just a coding convention issue. This doesn't cause any problem to the plugin, because you can declare variables in JavaScript without putting the `var` keyword before it, as far as I know.
